// Flexible contexts: make a kind (Rooms), give it a tab, make lines into
// rooms where they are, accept a suggested kind, and arrange the tab bar.
import { mkdtempSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { launch, watchConsole, shot, outline, assert, BASE, sleep } from './lib.mjs'

const { ctx, close } = await launch({ userDataDir: mkdtempSync(join(process.env.TMPDIR ?? tmpdir(), 'gs-ctx-')) })
const page = ctx.pages()[0] ?? (await ctx.newPage())
const errors = watchConsole(page)
const tabs = () => page.$$eval('.nav-tab', (els) => els.map((e) => e.textContent.trim()))
const sheet = (text) => page.tap(`.sheet-action:has-text("${text}")`)

await page.goto(BASE + '/')
await page.waitForSelector('.outline .row')
await sleep(500)
assert(JSON.stringify(await tabs()) === JSON.stringify(['Pads', 'Places', 'Contexts', 'Search', 'Settings']), 'Places has a tab; People is under Contexts: ' + JSON.stringify(await tabs()))

// A new kind, from the Contexts tab.
await page.tap('.nav-tab:has-text("Contexts")')
await page.waitForSelector('.contexts-page')
const kinds = await page.$$eval('.contexts-page .list-item .list-label', (els) => els.map((e) => e.textContent))
assert(JSON.stringify(kinds.slice(0, 2)) === JSON.stringify(['Places', 'People']), 'Contexts lists every kind: ' + JSON.stringify(kinds))
await page.tap('text=New kind')
await page.waitForSelector('.dialog-input')
await page.fill('.dialog-input', 'Rooms')
await page.tap('.dialog .btn-primary')
await page.waitForSelector('.category-page')
await sleep(300)
assert((await page.innerText('.page-title')).includes('Rooms'), 'opens the new kind')

// Add one there, then give Rooms a tab.
await page.fill('.add-input', 'Garage')
await page.tap('.add-form .btn-primary')
await page.waitForSelector('.title-block')
await sleep(300)
assert(await page.isVisible('.kind-tag:has-text("Rooms")'), 'a room’s page shows its kind')
await page.goBack()
await page.waitForSelector('.category-page')
await page.tap('[aria-label="Options for Rooms"]')
await sheet('Give it a tab in the bar')
await sleep(400)
assert((await tabs()).includes('Rooms'), 'Rooms has a tab now: ' + JSON.stringify(await tabs()))

// Lines in a list become rooms where they are.
await page.goto(BASE + '/#/pads')
await page.tap('text=New pad')
await page.waitForSelector('.editable.title')
await sleep(200)
await page.keyboard.type('House')
await page.keyboard.press('Enter')
await page.keyboard.type('- Kitchen')
await sleep(600)
await page.tap('[aria-label="More actions"]')
await sheet('Make it a context')
await sheet('Rooms')
await sleep(500)
assert(await page.isVisible('.row.context:has-text("Kitchen")'), 'Kitchen is a room, still in its list')
await page.keyboard.press('End')
await page.keyboard.press('Enter')
await page.keyboard.type('Basement')
await page.keyboard.press('Enter')
await page.keyboard.type('Wipe the counters in @')
await page.waitForSelector('.picker')
await page.keyboard.type('kitch')
await sleep(300)
const hit = await page.$eval('.picker-item', (e) => e.innerText.replace(/\s+/g, ' ').trim())
assert(hit === 'Kitchen Room in House', '@ shows what kind it is: ' + hit)
await page.tap('.picker-item')
await sleep(300)
await page.keyboard.press('Enter')
await page.keyboard.type('Sweep the floor in @')
await page.waitForSelector('.picker')
await page.keyboard.type('basem')
await sleep(300)
await page.tap('.picker-item:has-text("Basement")')
await sleep(300)
await page.tap('[aria-label="Hide keyboard"]')
await sleep(800)
await shot(page, 'contexts-house')

// Basement isn't a room yet, but it's linked to like one.
await page.tap('.nav-tab:has-text("Contexts")')
await page.waitForSelector('.contexts-page')
await sleep(400)
assert(await page.isVisible('.list-item:has-text("Basement") .suggest-btn:has-text("Rooms?")'), 'Contexts suggests Rooms for Basement')
await shot(page, 'contexts-tab')
await page.tap('.list-item:has-text("Basement") .suggest-btn')
await sleep(500)
await page.tap('.nav-tab:has-text("Rooms")')
await page.waitForSelector('.category-page')
await sleep(300)
const rooms = await page.$$eval('.category-page .list-label', (els) => els.map((e) => e.textContent))
assert(JSON.stringify(rooms) === JSON.stringify(['Basement', 'Garage', 'Kitchen']), 'Rooms: ' + JSON.stringify(rooms))
await shot(page, 'rooms')

// The bar: three kinds at most.
await page.goto(BASE + '/#/settings')
await page.waitForSelector('.nav-card')
await page.tap('.nav-card .list-item:has-text("People") .pin-toggle')
await sleep(400)
assert(JSON.stringify(await tabs()) === JSON.stringify(['Pads', 'Places', 'People', 'Rooms', 'Contexts', 'Search', 'Settings']), 'three kinds pinned: ' + JSON.stringify(await tabs()))
await page.tap('.nav-card button:has-text("New kind of context")')
await page.fill('.dialog-input', 'Projects')
await page.tap('.dialog .btn-primary')
await sleep(400)
await page.tap('.nav-card .list-item:has-text("Projects") .pin-toggle')
await sleep(300)
assert(await page.isVisible('.toast:has-text("Up to 3 kinds")'), 'a fourth needs another taken out first')
await page.tap('.nav-card .list-item:has-text("Places") .pin-toggle')
await sleep(400)
assert(!(await tabs()).includes('Places'), 'Places can leave the bar too')
await shot(page, 'tabs-settings')

console.log('console errors:', errors.length ? errors : 'none')
await close()
if (errors.length) process.exit(1)
